### ISSUE TITLE
ACI - Home Page - Header adjustment  

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_conscious_internet#1]
![Screen Shot 2021-02-08 at 2 06 22 PM](https://user-images.githubusercontent.com/78421574/107225136-ba29e800-6a18-11eb-8bd8-cf7fb4e75293.png)

The header needs to be adjusted: 
Alliance for a 
Conscious Internet

**Comment by AlexandreHannelas** [comment]
![Screen Shot 2021-02-15 at 5 15 46 PM](https://user-images.githubusercontent.com/78421574/107970499-7ce1cf00-6fb1-11eb-9655-cfe47a5a9b81.png)

Headline didn't change.

Needs to be: 
Alliance for a 
Conscious Internet

**Comment by Vilnite** [comment]
Done.
<img width="1169" alt="Screenshot 2021-02-15 at 18 36 11" src="https://user-images.githubusercontent.com/20182572/107972797-077bfb80-6fbd-11eb-8d14-07228fa67ea0.png">
