### ISSUE TITLE
ACI - add pagination to people's page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_conscious_internet#14]

**Comment by Vilnite** [comment]
Don't see it.
Can you please double check that we have pagination for both people and projects pages:

<img width="1190" alt="Screenshot 2021-02-15 at 12 33 44" src="https://user-images.githubusercontent.com/20182572/107935504-257c3880-6f8a-11eb-97dc-ab34e8a40785.png">
<img width="1145" alt="Screenshot 2021-02-15 at 12 33 35" src="https://user-images.githubusercontent.com/20182572/107935515-28772900-6f8a-11eb-9cc4-98462b72ea8a.png">

**Comment by samaradel** [comment]
works now

**Comment by Vilnite** [comment]
team page doesn't show content now:

<img width="1440" alt="Screenshot 2021-02-15 at 14 01 42" src="https://user-images.githubusercontent.com/20182572/107944129-5d897880-6f96-11eb-952b-2c5d41b3a11b.png">

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/107949399-e3f58880-6f9d-11eb-92a7-50e9064b715e.png)

fixed

**Comment by Vilnite** [comment]
pagination is gone
