### ISSUE TITLE
ACI - update footer with legal

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_conscious_internet#19]
Need to add legal to aci footer:

- Terms & Conditions >>> https://new.threefold.io/info/legal#/legal__terms_conditions_websites
- Privacy Policy >>> https://new.threefold.io/info/legal#/legal__privacypolicy
- Impressum >>> N/A (needs to be created)

**Comment by Sacha96** [comment]
updated issue relating to https://github.com/threefoldfoundation/home/issues/123
