### ISSUE TITLE
ACI - add filter bar for people page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_conscious_internet#27]
Add filter bar and filter out `memberships: aci, wisdom_council, grid_guardians, technology_council`

<img width="1188" alt="Screenshot 2021-03-17 at 12 35 32" src="https://user-images.githubusercontent.com/20182572/111454510-6009fa00-871d-11eb-8ed9-ede0ff977cb5.png">

Please see if possible to change `aci` to `aci_members` instead, so that filter bar dropdown shows:
ACI Members
Wisdom Council
Grid Guardians
Technology Council

Thank you :)

**Comment by samaradel** [comment]
done and ```aci_members``` will show in dropdown menu when it updates in [data_threefold](https://github.com/threefoldfoundation/data_threefold) repo
