### ISSUE TITLE
ACI: Fix metadata

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_conscious_internet#31]
- Alliance for a Conscious Internet | ACI
- A planetary movement of people and organisations that take action now to shape a conscious digital world that empowers everyone equally, across borders.
- Use image from header on website

Please let me know if anything else is needed

<img width="513" alt="Screen Shot 2021-03-22 at 4 47 39 PM" src="https://user-images.githubusercontent.com/50134479/111999843-6be72900-8b2e-11eb-8731-e479a59130ea.png">

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/112467311-94aa3100-8d6f-11eb-8dc3-c00f09cb42d9.png)

**Comment by samtaggart** [comment]
Can we make the title **Alliance for a Conscious Internet | ACI** please?

**Comment by samaradel** [comment]
> Can we make the title **Alliance for a Conscious Internet | ACI** please?

Done and the meta will update next merge to production
