### ISSUE TITLE
ACI - Wisdom Council - Card component styles and design

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_conscious_internet#6]
Ive added Wisdom Council team on wisdom council page using Cards component. It is not adjusted according to the style of the website and does not show all necessary information. 
It should:

- [x] Show images in the same size
- [x] Show company, website and location data from MD files
- [x] Show video links not in a new window but as a popup window.

See https://www.consciousinternet.org/#/people/sophie_monpeyssen, https://www.consciousinternet.org/#/council for design reference.

**Comment by samaradel** [comment]
@nbabenko design reference links refer to home page.. please provide another reference

**Comment by nbabenko** [comment]
here it is: https://www.consciousinternet.org/wisdomcouncil
https://github.com/threefoldfoundation/www_conscious_internet/tree/development/content/page/wisdomcouncil
